project:
  type: book

# apparently not (yet) used by Quarto
license: "CC BY"

latex-auto-install: true

crossref:
  fig-prefix: figure     # (default is "Figure")
  tbl-prefix: tableau    # (default is "Table")
  sec-prefix: section    # (default is "Section")

# setting fr-FR causes the date to be in english?
lang: fr
# language: _language.yml   # customized, "tableau" plutôt que "table", etc.

book:

  title: "Analyse et conception de logiciels"
  cover-image: images/cover.png
  image: images/wordle_ordre_alph.png

  # web site options
  favicon: images/favicon.ico
  # twitter-card: true
  search: true
  repo-url: https://github.com/fuhrmanator/log210-ndc-quarto/
  repo-actions: [issue]
  downloads: [pdf, epub]

  author: 
    - "Christopher Fuhrman"
    - "Yvan Ross"
  date: last-modified
  date-format: "DD MMMM YYYY à HH:mm:ss Z"

  chapters:
  - index.qmd # Preface
  - AnalyseConception.qmd
  - Besoins.qmd
  - CasUtilisation.qmd
  - MDD.qmd
  - DSS.qmd
  - GRASP.qmd
  - DetteTechnique.qmd
  - Contrats.qmd
  - RDCU.qmd
  - TDD.qmd
  - Réusinage.qmd
  - TravailEquipe.qmd
  - Outils-UML.qmd
  - GRASP-GoF.qmd
  - Fiabilité.qmd
  - DiagrammesActivites.qmd
  - DiagrammesEtats.qmd
  - ConceptionPackages.qmd
  - DiagrammesDeploiement.qmd
  - Laboratoires.qmd
  - references.qmd
  appendices:
    - Annexe_Cas_utilisation_Réserver_livre.qmd
    - Annexe_Cas_utilisation_Traiter_vente.qmd
    - Annexe_Cas_utilisation_Ouvrir_caisse.qmd

bibliography: references.bib
csl: ets
citations-hover: true
link-citations: true # pandoc setting
latex-auto-mk: true
link-external-icon: true

# Don't set colors here - only link color works, and it overrides the HTML theme: option. 
#  For the PDF version, I put them in the pdf: options below
# toccolor: blue
# urlcolor: Green4
# citecolor: violet
#linkcolor: violet


appendix-style: default

format:

  epub: 
    epub-cover-image: images/cover.png
    fig-format: png

  html:
    title-block-banner: true
    include-in-header: 
      - html-hacks/load-font-awesome.html
      - html-hacks/load-xkcd-font.html
    resources: web-resources/**
    # https://quarto.org/docs/output-formats/html-themes.html#overview
    theme: Spacelab
    
  pdf:
    # PRE quarto 1.3: has to be latexmk for .plantuml plugin to work (because it generates .svg files)
    pdf-engine: pdflatex

    template: partials/template.tex

    colorlinks: true
    documentclass: scrbook
    classoption: 
      # Remove odd-even page breaks (for printing PDF)
      - open=any
      - twoside=false # don't use even/odd pages, no blank pages
      # pass french to book class (babel will see it automatically)
      - french
    toc: false
    urlcolor: Green4
    citecolor: violet
    linkcolor: violet

    hyperrefoptions: 
      - pdfdisplaydoctitle=true
    highlight-style: github
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fontfamily: libertinus
    fontfamilyoptions: 
      # causes numbers to drop below the line, and a 0 by itself looks like an o
      # - osf
      - p
    fontsize: 12pt
    include-in-header: 
      - tex-hacks/color-tables.tex
      - tex-hacks/code-font.tex
      - tex-hacks/fix-unicode-chars.tex
      - tex-hacks/redefine-title-page.tex

    include-before-body: 
      - tex-hacks/redefine-parts-layout.tex

    # ragged2e is for the \justifying, see https://github.com/quarto-dev/quarto-cli/discussions/1534)
    header-includes: |
      \usepackage{ragged2e}


# filters must be run in the proper order here
filters:
  - filters/diagram-generator.lua
  - filters/fr-nbsp.lua
  - quarto
  - filters/inline-svg.lua
  - filters/pandoc-quotes.lua

#
# Note: If JAVA_HOME, PLANTUML and DOT system variables are correctly set 
# (and the tools they point to are installed), 
# you should not need the following meta data variables
#

# javaPath: C:/Program Files/Java/jdk1.8.0_331/bin/java.exe
# plantumlPath: G:/My Drive/PlantUML/plantuml.jar
# dotPath: C:/Program Files/Graphviz/bin/dot.exe

### citation info
