project:
  type: book

license: "CC BY-SA"


latex-auto-install: true

crossref:
  fig-prefix: figure     # (default is "Figure")
  tbl-prefix: tableau    # (default is "Table")

# setting fr-FR causes the date to be in english?
lang: fr
# language: _language.yml   # customized, "tableau" plutôt que "table", etc.

book:

  title: "Analyse et conception de logiciels"
  cover-image: images/cover.png
  image: images/wordle_ordre_alph.png
  
  author: 
    - "Christopher Fuhrman"
    - "Yvan Ross"
  date: last-modified
  date-format: "DD MMMM YYYY à HH:mm:ss Z"

  chapters:
  - index.qmd # Preface
  - part: Théorie
    chapters:
    - AnalyseConception.qmd
    - Besoins.qmd
    - CasUtilisation.qmd
    - MDD.qmd
    - DSS.qmd
    - GRASP.qmd
    - DetteTechnique.qmd
    - Contrats.qmd
    - RDCU.qmd
    - TDD.qmd
    - Réusinage.qmd
    - TravailEquipe.qmd
    - Outils-UML.qmd
    - GRASP-GoF.qmd
    - Fiabilité.qmd
    - DiagrammesActivites.qmd
    - DiagrammesEtats.qmd
    - ConceptionPackages.qmd
    - DiagrammesDeploiement.qmd
    - Laboratoires.qmd
    - references.qmd
  - part: Exercices
    chapters:
    - Exercice_Critique_d-une_conception.qmd
    - Exercice_Coder_des_méthodes_des_DS.qmd
  appendices:
   - Annexe_Cas_utilisation_Réserver_livre.qmd
   - Annexe_Cas_utilisation_Traiter_vente.qmd
   - Annexe_Cas_utilisation_Ouvrir_caisse.qmd
  # repo-actions: [source, issue]

bibliography: references.bib
csl: ets
citations-hover: true
citation-location: document
link-citations: true # pandoc setting
# citeproc: true # causes quarto to hang
# latex-auto-install: true
latex-auto-mk: true
link-external-icon: true

# Don't set colors here - only link color works, and it overrides the HTML theme: option. 
#  For the PDF version, I put them in the pdf: options below
# toccolor: blue
# urlcolor: Green4
# citecolor: violet
#linkcolor: violet


appendix-style: default

format:

  epub: 
    epub-cover-image: images/cover.png
    fig-format: png

  html:
    title-block-banner: true
    header-includes: |
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
            rel="stylesheet" data-external="1"/>
      <style type="text/css">
        @font-face {
          font-family: 'xkcd Script';
          src: url('web-resources/xkcd-font/xkcd-script.ttf') format('truetype');
        }
      </style>
    # https://quarto.org/docs/output-formats/html-themes.html#overview
    resources: web-resources/**
    theme: Spacelab
    

  pdf:
    # PRE 1.3: has to be latexmk for .plantuml plugin to work (because it generates .svg files)
    pdf-engine: pdflatex

    template: partials/template.tex

    colorlinks: true
    documentclass: scrbook
    classoption: 
      # Remove odd-even page breaks (for printing PDF)
      - open=any
      # pass french to book class (babel will see it automatically)
      - french
    toc: true
    toc-depth: 2
    toccolor: blue
    urlcolor: Green4
    citecolor: violet
    linkcolor: violet

    lof: true
    lot: true
    hyperrefoptions: 
      - pdfdisplaydoctitle=true
    highlight-style: github
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fontfamily: libertinus
    fontfamilyoptions: 
      - osf
      - p
    fontsize: 12pt
    include-in-header: 
      - tex-hacks/color-tables.tex
      - tex-hacks/code-font.tex
      - tex-hacks/fix-unicode-chars.tex
      - tex-hacks/redefine-title-page.tex
    # header-includes: |
    #   \frenchsetup{PartNameFull=false}

    include-before-body: 
      - tex-hacks/redefine-parts-layout.tex

# filters must be run in the proper order here
filters:
  - filters/fr-nbsp.lua
  - filters/diagram-generator.lua
  - quarto
  - filters/inline-svg.lua
  - filters/pandoc-quotes.lua

#
# Note: If JAVA_HOME, PLANTUML and DOT system variables are correctly set 
# (and the tools they point to are installed), 
# you should not need the following meta data variables
#

# javaPath: C:/Program Files/Java/jdk1.8.0_331/bin/java.exe
# plantumlPath: G:/My Drive/PlantUML/plantuml.jar
# dotPath: C:/Program Files/Graphviz/bin/dot.exe

### citation info
