# Identifier GRASP dans GoF

Dans cet exercice, vous allez mieux comprendre la relation entre les principes GRASP et les patrons GoF.

Nous rappelons le modèle pour décortiquer le patron Adaptateur, illustré à la @fig-Ex_Fig23_3.

```{.plantuml #fig-Ex_Fig23_3 caption="Adaptateur et principes GRASP [voir @craig_uml_2005, figure **A26.3/F23.3**]"}
!include figF23_3.pumlinclude
```

Une bonne ressource pour les patterns GoF est la suivante:

[https://fuhrmanator.github.io/oodp-horstmann/htm/index\_fr\_en.html](https://fuhrmanator.github.io/oodp-horstmann/htm/index_fr_en.html)

::: {.callout-tip}
Il se peut que certains principes GRASP ne s'appliquent pas à un patron GoF!
:::

## Itérateur

Identifiez les 4 principes GRASP dans le patron
[Itérateur](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=long%20d'un%20mur.-,Patron%20It%C3%A9rateur,Contexte,-un%20agr%C3%A9gat%20est),
selon les directives à la @sec-GRASP_Adaptateur.

## Observateur

Identifiez les 4 principes GRASP dans le patron
[Observateur](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=Contr%C3%B4leur-,patron%20observateur,-Mod%C3%A8le),
selon les directives à la @sec-GRASP_Adaptateur.


## Stratégie

Identifiez les 4 principes GRASP dans le patron
[Stratégie](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=page-,patron%20strategie,-Strat%C3%A9gie),
selon les directives à la @sec-GRASP_Adaptateur.


## Composite

Identifiez les 4 principes GRASP dans le patron
[Composite](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=composants-,patron%20composite,-Contexte),
selon les directives à la @sec-GRASP_Adaptateur.

## Décorateur

Identifiez les 4 principes GRASP dans le patron [Décorateur](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=d%C3%A9filement%20(Scroll%20Bars)-,Patron%20D%C3%A9corateur,Contexte,-Objets%20composant%20peuvent),
selon les directives à la @sec-GRASP_Adaptateur.

## Méthode Template
Identifiez les 4 principes GRASP dans le patron [Méthode Template](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch6/Ch6_fr.html#:~:text=java-,patron%20template%20method,-Contexte),
selon les directives à la @sec-GRASP_Adaptateur.

## Commande

Identifiez les 4 principes GRASP dans le patron [Commande](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch10/Ch10_fr.html#:~:text=java-,le%20patron%20command,-Contexte), selon les directives à la @sec-GRASP_Adaptateur.


## Méthode Fabrique

Identifiez les 4 principes GRASP dans le patron [Méthode fabrique](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch10/Ch10_fr.html#:~:text=methodes%20de%20fabrique%20(factory%20methods)), selon les directives à la @sec-GRASP_Adaptateur.


## Proxy

Identifiez les 4 principes GRASP dans le patron [Proxy](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch10/Ch10_fr.html#:~:text=de%20m%C3%A9thode%20distante-,Le%20patron%20PROXY,Contexte,-Une%20classe%20(le), selon les directives à la @sec-GRASP_Adaptateur.


## Façade

Identifiez les 4 principes GRASP dans le patron [Façade](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch7/Ch7_fr.html#:~:text=de%20propri%C3%A9t%C3%A9s-,La%20classe%20Fa%C3%A7ade,Un,-Bean%20est), selon les directives à la @sec-GRASP_Adaptateur.
