# Décortiquer les patterns GoF avec GRASP {#sec-GRASP-GoF}

Craig Larman a proposé les GRASP pour faciliter la compréhension des forces essentielles de la conception orientée-objet. Dans ce chapitre, on examine la présence des GRASP dans les patterns GoF. C'est une excellente façon de mieux comprendre et les principes GRASP et les patterns GoF.

## Exemple avec Adaptateur

Le chapitre A26/F23\ \faBook<i class="fa-solid fa-book"></i>\ présente l'exemple du pattern Adaptateur pour les calculateurs de taxes (@fig-Fig23_1 tirée du livre de Larman, Figure A26.3/F23.3).

```{.plantuml #fig-Fig23_1 caption="Le pattern Adaptateur."}
    @startuml
    skinparam class {
        BackgroundColor White
        FontSize 20
    }

    interface       IAdaptateurCalculTaxes
    class           AdaptateurTaxMaster implements IAdaptateurCalculTaxes
    class           AdaptateurGoodAsGoldTaxPro implements IAdaptateurCalculTaxes

    IAdaptateurCalculTaxes : getTaxes( Vente ) : Liste de ligneTaxes
    AdaptateurTaxMaster : getTaxes( Vente ) : Liste de ligneTaxes
    AdaptateurGoodAsGoldTaxPro : getTaxes( Vente ) : Liste de ligneTaxes
    @enduml
    ```

## Imaginer le code sans le pattern GoF

Chaque principe GRASP est défini avec un énoncé d'un problème de conception et une solution pour le résoudre. Pourtant, beaucoup d'exemples dans le livre de @craig_uml_2005 sont des patterns déjà appliqués (et le problème initial n'est pas toujours expliqué en détail). 

Alors, pour mieux comprendre l'application des patterns GoF, on doit imaginer la situation du logiciel *avant* l'application du pattern. Dans l'exemple avec l'adaptateur pour les calculateurs de taxes, imaginez le code si on n'avait aucun adaptateur. À la place d'une méthode `getTaxes()` envoyée par la classe Vente à l'adaptateur, on serait obligé de faire un branchement selon le type de calculateur de taxes externe utilisé actuellement (si on veut supporter plusieurs calculateurs). Donc, dans la classe Vente, il y aurait du code comme ceci:

```Java
/* calculateurTaxes est le nom du calculateur utilisé actuellement */
if(calculateurTaxes == "GoodAsGoldTaxPro") {
    /* série d'instructions pour interagir avec le calculateur */
} else if(calculateurTaxes == "TaxMaster") {
    /* série d'instructions pour interagir avec le calculateur */
} else if /* ainsi de suite pour chacun des calculateurs */
    /* ... */
}
```

Pour supporter un nouveau calculateur de taxes, il faudrait coder une nouvelle branche dans le bloc de `if/then`. 
Ça nuirait à la lisibilité du code et la méthode qui contient tout ce code deviendrait de plus en plus longue. 
Même si on faisait une méthode pour encapsuler le code de chaque branche, ça ferait toujours augmenter les responsabilités de la classe Vente. 
Elle est responsable de connaître tous les détails (l'API distinct et immuable) de chaque calculateur de taxe externe, puisqu'elle communique directement (il y a du couplage) à ces derniers.

Le pattern Adaptateur comprend les principes GRASP Faible couplage, Forte cohésion, Polymorphisme, Indirection, Fabrication pure et Protection des variations. La @fig-Fig23_3 (tirée du livre de Larman, Figure A26.3/F23.3) démontre la relation entre ces principes dans le cas d'Adaptateur.

```{.plantuml #fig-Fig23_3 caption="Adaptateur et principes GRASP [voir @craig_uml_2005, figure **A26.3/F23.3**]"}
!include figF23_3.pumlinclude
```

On peut donc voir le pattern adaptateur comme *une spécialisation* de plusieurs principes GRASP:

- Polymorphisme
- Indirection
- Fabrication pure
- Faible couplage
- Forte cohésion
- Protection des variations

Êtes-vous en mesure d'expliquer dans ce contexte comment Adaptateur est relié à ces principes? C'est-à-dire, pouvez-vous identifier les GRASP dans le pattern Adaptateur?

## Identifier les GRASP dans les GoF {#sec-GRASP_Adaptateur}

Pour identifier les principes GRASP dans un pattern GoF comme Adaptateur, on rappelle la définition de chaque principe GRASP et on essaie d'imaginer le problème qui pourrait exister et comment le principe (et le pattern GoF) résout le problème.

Référez-vous à la @fig-Fig23_1 du pattern Adaptateur pour les sections suivantes.

### Polymorphisme

Selon @craig_uml_2005:

::: {.callout}
**Problème:** Qui est responsable quand le comportement varie selon le type?  
**Solution:** Lorsqu'un comportement varie selon le type (classe), affectez la responsabilité de ce comportement -- avec des opérations polymorphes -- aux types pour lesquels le comportement varie.
:::

Le "comportement qui varie" est la manière d'adapter les méthodes utilisées par le calculateur de taxes choisi à la méthode `getTaxes()`. Alors, cette "responsabilité" est affectée au type interface `IAdaptateurCalculTaxes` (et ces implémentations) dans l'opération polymorphe `getTaxes()`.

### Fabrication pure

Selon @craig_uml_2005:

::: {.callout}
**Problème:** En cas de situation désespérée, que faire quand vous ne voulez pas transgresser les principes de faible couplage et de forte cohésion?  
**Solution:** Affectez un ensemble très cohésif de responsabilités à une classe "comportementale" artificielle qui ne représente pas un concept du domaine - une entité fabriquée pour augmenter la cohésion, diminuer le couplage et faciliter la réutilisation.
:::

La Fabrication pure est la classe "comportementale et artificielle" qui est la hiérarchie `IAdaptateurCalculTaxes` (comprenant chaque adaptateur concret). 
Elle est comportementale puisqu'elle ne fait qu'adapter des appels. 
Elle est artificielle puisqu'elle ne représente pas un élément dans le modèle du domaine. 

L'ensemble des adaptateurs concrets ont des "responsabilités cohésives" qui sont la manière d'adapter la méthode `getTaxes()` aux méthodes (immuables) des calculateurs de taxes externes. 
Elles ne font que ça. 
La cohésion est augmentée aussi dans la classe Vente qui n'a plus la responsabilité de s'adapter aux calculateurs de taxes externes. 
C'est le travail qui a été donné aux adaptateurs concrets. 

Le couplage est diminué, car la classe Vente n'est plus couplée directement aux calculateurs de taxes externes.
La réutilisation des calculateurs est facilitée, car la classe Vente ne doit plus être modifiée si l'on veut utiliser un autre calculateur externe.
Il suffit de créer un adaptateur pour ce dernier.

### Indirection

Selon @craig_uml_2005:

::: {.callout}
**Problème:** Comment affecter les responsabilités pour éviter le couplage direct?  
**Solution:** Pour éviter le couplage direct, affectez la responsabilité à un objet qui sert d'intermédiaire avec les autres composants ou services.
:::

Le "couplage direct" qui est évité est le couplage entre la classe Vente et les calculateurs de taxes externes. Le pattern Adaptateur (général) cherche à découpler le Client des classes nommées Adaptee, car chaque Adaptee a une API différente pour le même genre de "service". Alors, la responsabilité de s'adapter aux services différents est affectée à la hiérarchie de "classes intermédiaires", soit l'interface type IAdaptateurCalculTaxes et ses implémentations.

### Protection des variations

Selon @craig_uml_2005:

::: {.callout}
**Problème:** Comment affecter les responsabilités aux objets, sous-systèmes et systèmes de sorte que les variations ou l'instabilité de ces éléments n'aient pas d'impact négatif sur les autres?  
**Solution:** Identifiez les points de variation ou d'instabilité prévisibles et affectez les responsabilités afin de créer une "interface" stable autour d'eux.
:::

Les "variations ou l'instabilité" sont les calculateurs de taxes qui ne sont pas sous le contrôle des développeurs du projet (ce sont des modules externes ayant chacun une API différente). Quant à "l'impact négatif sur les autres", il s'agit des modifications que les développeurs auraient à faire sur la classe Vente chaque fois que l'on décide de supporter un autre calculateur de taxes (ou si l'API de ce dernier évolue). 

Quant aux "responsabilités" à affecter, c'est la fonctionnalité commune de tous les calculateurs de taxes, soit le calcul de taxes. Pour ce qui est de "l'interface stable", il s'agit de la méthode `getTaxes()` qui ne changera jamais. Elle est définie dans le type-interface IAdaptateurCalculTaxes. Cette définition isole (protège) la classe Vente des modifications (ajout de nouveaux calculateurs ou changements de leur API). 

## GRASP et réusinage

Il y a des liens entre les GRASP et les activités de [Réusinage (Refactorisation)](#sec-Refactoring). 
Alors, un IDE qui automatise les *refactorings* peut vous aider à appliquer certains GRASP.

- GRASP Polymorphisme est relié à [Replace Type Code with Subclasses](https://refactoring.com/catalog/replaceTypeCodeWithSubclasses.html) et [Replace conditional with polymorphism](https://refactoring.com/catalog/replaceConditionalWithPolymorphism.html) -- attention, il vaut mieux appliquer ce dernier seulement quand il y a des instructions conditionnelles (`switch`) répétées à plusieurs endroits dans le code.
- GRASP Fabrication pure est relié à [Extract class](https://refactoring.com/catalog/extractClass.html).
- GRASP Indirection est relié à [Extract function](https://refactoring.com/catalog/extractFunction.html) et [Move function](https://refactoring.com/catalog/moveFunction.html).

## Exercices

Pour ces exercices, suivre le modèle pour décortiquer le patron Adaptateur, illustré à la @fig-Ex_Fig23_3.

Une bonne ressource pour les patterns GoF est la suivante:

[https://fuhrmanator.github.io/oodp-horstmann/htm/index\_fr\_en.html](https://fuhrmanator.github.io/oodp-horstmann/htm/index_fr_en.html)

::: {.callout-tip}
Il se peut que certains principes GRASP ne s'appliquent pas à un patron GoF!
:::

::: {#exr-GRASP_iterateur}

### Itérateur

Identifiez les 4 principes GRASP dans le patron
[Itérateur](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=Patron-,iterateur,-Contexte),
selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-GRASP_observateur}

### Observateur

Identifiez les 4 principes GRASP dans le patron
[Observateur](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=Contr%C3%B4leur-,patron%20observateur,-Mod%C3%A8le),
selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-GRASP_strategie}

### Stratégie

Identifiez les 4 principes GRASP dans le patron
[Stratégie](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=page-,patron%20strategie,-Strat%C3%A9gie),
selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-GRASP_composite}

### Composite

Identifiez les 4 principes GRASP dans le patron
[Composite](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=composants-,patron%20composite,-Contexte),
selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-GRASP_decorateur}

### Décorateur

Identifiez les 4 principes GRASP dans le patron [Décorateur](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch5/Ch5_fr.html#:~:text=d%C3%A9filement%20(Scroll%20Bars)-,Patron%20D%C3%A9corateur,Contexte),
selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-GRASP_methode_template}

### Méthode Template
Identifiez les 4 principes GRASP dans le patron [Méthode Template](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch6/Ch6_fr.html#:~:text=java-,patron%20template%20method,-Contexte),
selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-GRASP_commande}

### Commande

Identifiez les 4 principes GRASP dans le patron [Commande](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch10/Ch10_fr.html#:~:text=java-,le%20patron%20command,-Contexte), selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-GRASP_methode_fabrique}

### Méthode Fabrique

Identifiez les 4 principes GRASP dans le patron [Méthode fabrique](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch10/Ch10_fr.html#:~:text=methodes%20de%20fabrique%20(factory%20methods)), selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-GRASP_proxy}

### Proxy

Identifiez les 4 principes GRASP dans le patron [Proxy](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch10/Ch10_fr.html#:~:text=de%20m%C3%A9thode%20distante-,Le%20patron%20PROXY,Contexte,-Une%20classe), selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-GRASP_facade}

### Façade

Identifiez les 4 principes GRASP dans le patron [Façade](https://fuhrmanator.github.io/oodp-horstmann/htm/Ch7/Ch7_fr.html#:~:text=la%20classe%20fa%C3%A7ade-,le%20pattern%20facade,-Contexte), selon les directives à la @sec-GRASP_Adaptateur.

:::

::: {#exr-Adaptater}

### Adaptateur

Proposez une mise en oeuvre du patron GoF Adaptateur pour un système de livraison qui peut être configuré avec trois variantes du service de calcul d'itinéraires:

- [Google Maps](https://developers.google.com/maps/documentation/directions)
- [Bing Maps](https://www.microsoft.com/en-us/maps/routing#routing)
- [Apple Maps](https://developer.apple.com/documentation/mapkitjs/)

Le système veut obtenir une liste d'étapes (des directions) pour se rendre à une destination à partir d'un point de départ.
L'utilisateur du système pourra décider lequel des services lui convient dans les préférences.

Le but de l'exercice est de déterminer l'interface stable (Protection des variations GRASP) étant donné les variantes des services de calcul d'itinéraires.
Cela peut être un diagramme de classe réalisé avec PlantUML.

:::